import { createScopedLogger } from '~/utils/logger';
import type { GeneratedFile } from '~/types/generation';

const logger = createScopedLogger('ContentValidator');

export interface ValidationResult {
  valid: boolean;
  reason?: string;
  filesDetected: string[];
}

/**
 * Validates that ONLY content.ts was generated.
 * Called AFTER LLM completes its response.
 *
 * @param files - Array of all files generated by LLM
 * @returns ValidationResult with pass/fail status
 */
export function validateContentGeneration(files: GeneratedFile[]): ValidationResult {
  const EXPECTED_FILENAME = 'content.ts';

  // Case 1: No files generated
  if (files.length === 0) {
    logger.warn('[VALIDATION] ✗ No files generated');
    return {
      valid: false,
      reason: 'No files were generated',
      filesDetected: [],
    };
  }

  // Case 2: Multiple files generated
  if (files.length > 1) {
    logger.warn('[VALIDATION] ✗ Multiple files generated', {
      count: files.length,
      files: files.map((f) => f.path),
    });
    return {
      valid: false,
      reason: `Expected only ${EXPECTED_FILENAME}, but ${files.length} files were generated`,
      filesDetected: files.map((f) => f.path),
    };
  }

  // Case 3: Exactly 1 file - check if it's content.ts (regardless of path)
  const fileName = getFileName(files[0].path);

  if (fileName !== EXPECTED_FILENAME) {
    logger.warn('[VALIDATION] ✗ Wrong file generated', {
      expected: EXPECTED_FILENAME,
      actual: fileName,
      fullPath: files[0].path,
    });
    return {
      valid: false,
      reason: `Expected ${EXPECTED_FILENAME}, but got ${fileName}`,
      filesDetected: [files[0].path],
    };
  }

  // Case 4: Valid - exactly content.ts
  logger.info('[VALIDATION] ✓ Valid: Only content.ts generated', {
    path: files[0].path,
    contentLength: files[0].content.length,
  });

  return {
    valid: true,
    filesDetected: [files[0].path],
  };
}

/**
 * Extract filename from a path (handles any path format).
 * Examples:
 * - src/data/content.ts → content.ts
 * - /home/project/src/data/content.ts → content.ts
 * - content.ts → content.ts
 */
function getFileName(path: string): string {
  // Find the last slash (works for both / and \)
  const lastSlash = Math.max(path.lastIndexOf('/'), path.lastIndexOf('\\'));

  // If no slash found, the entire path is the filename
  if (lastSlash === -1) {
    return path;
  }

  // Extract everything after the last slash
  return path.substring(lastSlash + 1);
}
